#!/bin/sh
set -e

MODULE_NAME=cmemdrv-dkms
MODULE_VERSION=1.0.0
if [ "$1" = "configure" ]; then
    dkms add -m ${MODULE_NAME} -v ${MODULE_VERSION}
    dkms build -m ${MODULE_NAME} -v ${MODULE_VERSION}
    dkms install -m ${MODULE_NAME} -v ${MODULE_VERSION}
fi


exit 0
